version: "3"
services:
  
  siteextract-backend:
    build:
      context: backend/
    image: siteextract-backend
    container_name: siteextract-backend
    restart: unless-stopped
    volumes:
      - "${CONFIG_PATH}:/src/config"
      - "${PLUGIN_PATH}:/src/plugin/plugin"
      - "${LOG_PATH}:/src/log"
      - "${DATA_PATH}:/src/data"
  
  siteextract-frontend:
    build:
      context: frontend/
      args:
        BASENAME: "${FRONTEND_BASENAME}"
        BACKEND_URL: "${FRONTEND_BASENAME}"
    image: siteextract-frontend
    container_name: siteextract-frontend
    restart: unless-stopped
  
  siteextract-nginx:
    image: nginx:alpine
    container_name: siteextract-nginx
    restart: unless-stopped
    ports:
      - ${APP_PORT}:80
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
      NGINX_FRONTEND_BASENAME: "${FRONTEND_BASENAME}"
    depends_on:
      - siteextract-backend
      - siteextract-frontend
    volumes:
      - ./nginx.conf:/etc/nginx/templates/nginx.conf.template